app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories
  root 'category#index'
end

app/app/models/category.rb
class Category < ApplicationRecord
end

app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  #Listing the categories
  def index
    @categories=Category.all
  end

  def show
    @category=Category.find(params[:id])
  end

  def new
  @category=Category.new
  end

  def edit
   @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
    redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

end

app/app/helpers/categories_helper.rb
module CategoriesHelper
end

app/app/views/categories/edit.html.erb
<%= form_for @category do  |f| %>
<p>
<%= f.label :name %>
<%=f.text_field :name %>
</p>
<p>
<%= f.submit %><br>
</p>
<% end %>

app/app/views/categories/index.html.erb
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>created_at</th>
    <th>updated_at</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
    <td><%=category.id%></td>
      <td><%= category.name %></td>
        <td><%= category.created_at %></td>
        <td><%= category.updated_at %></td>
      <td><%= link_to 'show', category_path(category) %></td>
      <td><%= link_to 'destroy', category_path(category.try(:id)), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/app/views/categories/new.html.erb
<%= form_for @category   do |f| %>
<p>
<%= f.label :name %>
<%=f.text_field :name %>
</p>
<p>
<%= f.submit %><br>
</p>
<% end %>

app/app/views/categories/show.html.erb
<p>
<STRONG>Id</STRONG>
<%=@category.id%><br>
<Strong>Name</Strong>
<%=@category.name %>
</p>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>